mmap.hpp: Add missing header file
gcc-11 Fails to build wit this error:

mmap.hpp: In member function ‘bool MMap::file(reflex::Input&, const char*&, size_t&)’:
mmap.hpp:90:176: error: ‘numeric_limits’ is not a member of ‘std’

Complete log:
https://people.debian.org/~doko/logs/20210228/filtered/gcc11/ugrep_3.1.9+dfsg-1_unstable_gcc11.log

Signed-off-by: Ricardo Ribalda <ricardo@ribalda.com>